---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: gateway-service
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: gateway-service
  template:
    metadata:
      labels:
        run: gateway-service
        visualize: "true"
    spec:
      containers:
        - name: gateway-service
          image: arthurstrokov/gateway-service:v0.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVER-PORT
              value: "8080"
            - name: EUREKA-DEFAULT-ZONE
              value: "http://192.168.59.106:30001/eureka"
            - name: EUREKA-INSTANCE-HOSTNAME
              value: gateway-service
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: gateway-service
  name: gateway-service
  annotations:
    haproxy.org/check: "enabled"
    haproxy.org/forwarded-for: "enabled"
    haproxy.org/load-balance: "roundrobin"
    haproxy.org/path-rewrite: /
spec:
  selector:
    run: gateway-service
  ports:
    - name: gateway-service-port
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
