spring:
  main:
    banner-mode: off
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
---
server:
  port: ${SERVER-PORT:8888}
---
eureka:
  instance:
    appname: gateway-service
  client:
    service-url:
      defaultZone: ${EUREKA-DEFAULT-ZONE:http://localhost:8761/eureka}
    register-with-eureka: true
