eureka:
  instance:
    appname: gateway-service
  client:
    service-url:
      defaultZone: ${EUREKA-DEFAULT-ZONE:http://localhost:8761/eureka}
    register-with-eureka: true
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  application:
    name: gateway-service